### ISSUE TITLE
Load Balancer Not Working When Provisioning on Public Network

### ISSUE THREAD

**Issue by ching-kuo** [cloud-native-taiwan/Infra-Labs-Docs#30]
@tico88612 reported that their load balancer isn't working after the upgrade. The load balancer is directly connected to public network and load balancing to private network.

After investigation, we suspect the correct way to use load balancer is to connect it in the private network and give it a floating IP.

We are currently awaiting @tico88612 on testing if this method works.

**Comment by tico88612** [comment]
The test result was successful.

Create a load balancer give it private network IP for private network, and click `Associate Floating IP` to get public floating IP, you can use an external network connection to access.
