### ISSUE TITLE
貢獻自行研究的專案

### ISSUE THREAD

**Issue by CCH0124** [cloud-native-taiwan/Infra-Labs-Docs#39]
雖然沒有使用這邊的資源，但能否在這邊能貢獻自行研究的專案。

**Comment by ching-kuo** [comment]
您好，

非常歡迎貢獻自行研究的專案。
謝謝！

**Comment by CCH0124** [comment]
您好，我想把實作文件貢獻至這邊的話，要如何進行 

謝謝

**Comment by ching-kuo** [comment]
您好，

可以參考先前的 PR

https://github.com/cloud-native-taiwan/Infra-Labs-Docs/pull/37
https://github.com/cloud-native-taiwan/Infra-Labs-Docs/pull/24

**Comment by CCH0124** [comment]
謝謝

**Comment by CCH0124** [comment]
I  send PR #47 .
