### ISSUE TITLE
Add Front Page

### ISSUE THREAD

**Issue by ching-kuo** [cloud-native-taiwan/Infra-Labs-Docs#5]
It will be better if we have some kind of front page hosting somewhere which will render these markdown.

This will make it easier for users to grasp informations.

**Comment by steveyiyo** [comment]
@iGene I suggest we can use [Hugo](https://gohugo.io/) as the front page. It supports markdown and hosting on GitHub.

For example:
- https://blog.steveyi.net/en/posts/as7480/
- https://github.com/steveyiyo/blog_source/blob/main/content/en/posts/as7480.md

If you think this idea works, I'd be happy to help!

**Comment by ching-kuo** [comment]
@steveyiyo 

Markdown should work. In this case I think it's better to open another repo dedicated for the website.
Really appreciate if you can help on this issue.

**Comment by steveyiyo** [comment]
Sure, I will do it this weekend.

**Comment by steveyiyo** [comment]
@ching-kuo Maybe we can create a new branch, and use [actions-hugo](https://github.com/peaceiris/actions-hugo) with GitHub Action to build the website.

It may be like [this](https://github.com/steveyiyo/blog_source) repo.

**Comment by steveyiyo** [comment]
I will make a task soon.

**Comment by tonyhhyip** [comment]
How about [asciidoctor](https://asciidoctor.org) or [Docusaurus](https://docusaurus.io)?

**Comment by steveyiyo** [comment]
[Docusaurus](https://docusaurus.io/) looks good! I will try it once update the documents.

Thanks to @tonyhhyip
