### ISSUE TITLE
Auto assign pull requests reviewer

### ISSUE THREAD

**Issue by tico88612** [cloud-native-taiwan/Infra-Labs-Docs#50]
As #49 mentioned, we need to auto assign our reviewer for each pull request.

**Comment by steveyiyo** [comment]
Hi @tico88612,

We can set up a CODEOWNERS file in the repo. This will automatically assign reviewers when a new Pull Request is submitted.

Ref: [About code owners](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners)

**Comment by tico88612** [comment]
LGTM, thank you!
