### ISSUE TITLE
Add Public Monitoring Page

### ISSUE THREAD

**Issue by ching-kuo** [cloud-native-taiwan/Infra-Labs-Docs#6]
We should have a public monitoring page for users to check current status of operations.

- OpenStack smoke test (code OK, need dashboard)
- ping latency test to gateway (103.122.118.253)

**Comment by steveyiyo** [comment]
@ching-kuo Direct monitoring of Juniper devices may not be a good idea, since their control plane may lead to ICMP latency unstable.

> Ref: https://supportportal.juniper.net/s/article/Junos-OS-ICMP-Ping-Showing-Latency-for-Host-Inbound-and-Outbound-traffic?language=en_US

Suggest monitoring latency of openstack.cloudnative.tw (103.122.118.253)

**Comment by ching-kuo** [comment]
@steveyiyo updated

**Comment by tico88612** [comment]
This is temporarily status page for Infra Labs.

Now is change on here. -> https://status.cloudnative.tw/

- 2023.03.08 Status page temporarily down, will be comeback soon.
- 2023.06.01 Status page come back!

**Comment by tico88612** [comment]
Resolved.
