### ISSUE TITLE
Add Current Configuration Files

### ISSUE THREAD

**Issue by ching-kuo** [cloud-native-taiwan/Infra-Labs-Docs#7]
Add current configurations files/deployment script to GitHub

**Comment by steveyiyo** [comment]
Hey @ching-kuo,

I see that you have merged #8. Can we close this issue?

Thank you!

**Comment by ching-kuo** [comment]
There is still more configurations that needed to be updated.

**Comment by ching-kuo** [comment]
This repo will be used only for documentation website, will create another repo for configuration files.
